services:
  mysql:
    image: mysql:8-debian # u can use any version of mysql
    container_name: mysql-testing-container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: CustomerDB
    ports:
      - "3306:3306"